version: 2
gomod:
  proxy: true

archives:
  - files:
      - LICENSE
      - README.md
      - legal/**/*

builds:
  - main: ./cmd/websrv/
    binary: websrv
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static" -s -w -X main.version={{.Version}}

dockers_v2:
  - images:
      - "ngergs/websrv"
    tags:
      - "latest"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "{{ .Tag }}"
    dockerfile: build/Dockerfile
    extra_files:
      - legal
